src/Entity/AccommodationDemand.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Enum\AccommodationDemandStatusEnum;
use App\Repository\AccommodationDemandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Fresh\DoctrineEnumBundle\Validator\Constraints as DoctrineAssert;

/**
 * @ORM\Entity(repositoryClass=AccommodationDemandRepository::class)
 */
class AccommodationDemand
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="accommodationDemands")
     * @ORM\JoinColumn(nullable=false)
     */
    private $young;

    /**
     * @var Accommodation
     *
     * @ORM\ManyToOne(targetEntity="Accommodation", inversedBy="accommodationDemands")
     * @ORM\JoinColumn(nullable=false)
     */
    private $accommodation;

    /**
     * @var string
     *
     * @ORM\Column(type="AccommodationDemandStatusType")
     * @DoctrineAssert\Enum(entity="App\Enum\AccommodationDemandStatusEnum")
     */
    private $status;

    /**
     * @var string
     *
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @var ThreadAccommodationDemand|null
     *
     * @ORM\OneToOne(targetEntity="ThreadAccommodationDemand", inversedBy="accommodationDemand", cascade={"persist", "remove"})
     */
    private $thread;

    /**
     * @var Cohabitation|null
     *
     * @ORM\OneToOne(targetEntity="Cohabitation", inversedBy="accommodationDemand", cascade={"persist", "remove"})
     */
    private $cohabitation;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="Association")
     */
    private $associations;

    /**
     * @var string|null
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $refusingExplanation;

    public function __construct()
    {
        $this->associations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getYoung(): User
    {
        return $this->young;
    }

    public function setYoung(User $young): void
    {
        $this->young = $young;
    }

    public function getAccommodation(): Accommodation
    {
        return $this->accommodation;
    }

    public function setAccommodation(Accommodation $accommodation): void
    {
        $this->accommodation = $accommodation;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    public function getThread(): ?ThreadAccommodationDemand
    {
        return $this->thread;
    }

    public function setThread(?ThreadAccommodationDemand $thread): void
    {
        $this->thread = $thread;

        if ($thread) {
            $thread->setAccommodationDemand($this);
        }
    }

    public function getCohabitation(): ?Cohabitation
    {
        return $this->cohabitation;
    }

    public function setCohabitation(?Cohabitation $cohabitation): void
    {
        $this->cohabitation = $cohabitation;
    }

    public function getAssociations(): Collection
    {
        return $this->associations;
    }

    public function getRefusingExplanation(): ?string
    {
        return $this->refusingExplanation;
    }

    public function setRefusingExplanation(?string $refusingExplanation): void
    {
        $this->refusingExplanation = $refusingExplanation;
    }

    public function getClassStatus(): string
    {
        switch ($this->status) {
            case AccommodationDemandStatusEnum::STATUS_PENDING:
            case AccommodationDemandStatusEnum::STATUS_AWAITING_USERS_APPROVAL:
                return 'pending';

            case AccommodationDemandStatusEnum::STATUS_ACCEPTED:
            case AccommodationDemandStatusEnum::STATUS_COMPLETED:
                return 'accepted';
        }

        return 'declined';
    }

    public function getSenior(): User
    {
        return $this->accommodation->getSenior();
    }

    public function addAssociation(Association $association): void
    {
        if (!$this->associations->contains($association)) {
            $this->associations->add($association);
        }
    }

    public function removeAssociation(Association $association): void
    {
        $this->associations->removeElement($association);
    }
}

src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use EmailChecker\Constraints as EmailCheckerAssert;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Email;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 *
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, \Serializable, PasswordAuthenticatedUserInterface
{
    use TimestampableEntity;

    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=180, unique=true, nullable=true)
     * @Assert\Email(mode=Email::VALIDATION_MODE_HTML5)
     * @EmailCheckerAssert\NotThrowawayEmail
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column
     */
    private $lastname;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday;

    /**
     * @var array
     *
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $password;

    /**
     * @var string|null
     */
    private $plainPassword;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @var Profile
     *
     * @ORM\OneToOne(targetEntity="Profile", inversedBy="user", cascade={"persist", "remove"})
     */
    private $profile;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="Message", mappedBy="sender", cascade={"persist", "remove"}))
     */
    private $messages;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="ThreadMetadata", mappedBy="participant", cascade={"persist", "remove"}))
     */
    private $threadMetadatas;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="ThreadFavorite", mappedBy="user", cascade={"persist", "remove"}))
     */
    private $threadFavorites;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Thread", mappedBy="users", cascade={"persist", "remove"})
     * @ORM\OrderBy({"lastMessageAt" : "DESC"})
     */
    private $threads;

    /**
     * @var Accommodation|null
     *
     * @ORM\OneToOne(targetEntity="Accommodation", mappedBy="senior", cascade={"persist", "remove"})
     */
    private $accommodation;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="AccommodationDemand", mappedBy="young", orphanRemoval=true)
     */
    private $accommodationDemands;

    /**
     * @var Location
     *
     * @ORM\OneToOne(targetEntity="Location", cascade={"persist", "remove"})
     */
    private $location;

    /**
     * @var Association|null
     *
     * @ORM\ManyToOne(targetEntity="Association", inversedBy="users")
     */
    private $association;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="Event", mappedBy="users", cascade={"persist", "remove"})
     * @ORM\OrderBy({"date" : "ASC"})
     */
    private $events;

    /**
     * @var UserNotification|null
     *
     * @ORM\OneToOne(targetEntity="UserNotification", cascade={"persist", "remove"})
     */
    private $userNotification;

    public function __construct()
    {
        $this->setProfile(new Profile());
        $this->messages = new ArrayCollection();
        $this->threads = new ArrayCollection();
        $this->threadMetadatas = new ArrayCollection();
        $this->threadFavorites = new ArrayCollection();
        $this->accommodationDemands = new ArrayCollection();
        $this->location = new Location();
        $this->events = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    public function getFirstname(): string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): void
    {
        $this->firstname = $firstname;
    }

    public function getLastname(): string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): void
    {
        $this->lastname = $lastname;
    }

    public function getBirthday(): ?\DateTime
    {
        return $this->birthday;
    }

    public function setBirthday(?\DateTime $birthday): void
    {
        $this->birthday = $birthday;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): void
    {
        $this->isVerified = $isVerified;
    }

    public function getProfile(): Profile
    {
        return $this->profile;
    }

    public function setProfile(Profile $profile): void
    {
        $this->profile = $profile;
        $profile->setUser($this);
    }

    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function getThreadMetadatas(): Collection
    {
        return $this->threadMetadatas;
    }

    public function getThreadFavorites(): Collection
    {
        return $this->threadFavorites;
    }

    public function getThreads(): Collection
    {
        return $this->threads;
    }

    public function getAccommodation(): ?Accommodation
    {
        return $this->accommodation;
    }

    public function setAccommodation(?Accommodation $accommodation): void
    {
        $this->accommodation = $accommodation;
        $accommodation->setSenior($this);
    }

    public function getAccommodationDemands(): Collection
    {
        return $this->accommodationDemands;
    }

    public function getLocation(): Location
    {
        return $this->location;
    }

    public function setLocation(Location $location): void
    {
        $this->location = $location;
    }

    public function getAssociation(): ?Association
    {
        return $this->association;
    }

    public function setAssociation(?Association $association): void
    {
        $this->association = $association;
    }

    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function getUserNotification(): ?UserNotification
    {
        return $this->userNotification;
    }

    public function setUserNotification(UserNotification $userNotification): void
    {
        $this->userNotification = $userNotification;
    }

    public function getFullName(): string
    {
        return $this->getFirstname().' '.$this->getLastname();
    }

    public function getUsername(): string
    {
        return $this->email;
    }

    public function getUserIdentifier(): string
    {
        return $this->getUsername();
    }

    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials(): void
    {
    }

    public function getAge(): ?int
    {
        $age = ($this->birthday instanceof \DateTimeInterface)
            ? date_diff(new \DateTime('now'), $this->birthday)->y
            : null;

        return (\is_int($age) && $age > 1) ? $age : null;
    }

    public function serialize(): string
    {
        return serialize([$this->id, $this->email, $this->password]);
    }

    public function unserialize($data): void
    {
        [
            $this->id,
            $this->email,
            $this->password
            ] = unserialize($data);
    }

    public function addMessage(Message $message): void
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setSender($this);
        }
    }

    public function removeMessage(Message $message): void
    {
        $this->messages->removeElement($message);
    }

    public function addThreadMetadata(ThreadMetadata $threadMetadata): void
    {
        if (!$this->threadMetadatas->contains($threadMetadata)) {
            $this->threadMetadatas->add($threadMetadata);
            $threadMetadata->setParticipant($this);
        }
    }

    public function removeThreadMetadata(ThreadMetadata $threadMetadata): void
    {
        $this->threadMetadatas->removeElement($threadMetadata);
    }

    public function addThreadFavorite(ThreadFavorite $threadFavorite): void
    {
        if (!$this->threadFavorites->contains($threadFavorite)) {
            $this->threadFavorites->add($threadFavorite);
            $threadFavorite->setUser($this);
        }
    }

    public function removeThreadFavorite(ThreadFavorite $threadFavorite): void
    {
        $this->threadFavorites->removeElement($threadFavorite);

templates/accommodation_demand/_message_refused_explanation.html.twig
<div class="text-center mt-3">
    <p>
        {{ 'accommodation_demand.message_footer.refusing_explanation'|trans }}
    </p>
    <p>{{ accommodationDemand.refusingExplanation }}</p>
</div>

templates/accommodation_demand/_sub_list.html.twig
<div class="py-4">
    <div class="titled-p">
        <div class="text">
            <div class="matches">
                {% for demand in accommodationDemands %}
                    <div class="match {{ demand.classStatus }}" data-controller="popup-on-click" data-popup-on-click-id-value="{{ demand.id }}">
                        <div class="profile">
                            {% if isSenior %}
                                {% set user = demand.young %}
                            {% else %}
                                {% set user = demand.senior %}
                            {% endif %}

                            {% if user != app.user %}
                                <div>
                                    {% include "user/_image_user.html.twig" %}
                                    <div class="name">
                                        <a href="{{ path('user_show', {'id': user.id}) }}">{{ user.fullName }}</a>
                                    </div>
                                </div>
                            {% endif %}

                            <div class="description">{{ demand.description }}</div>
                        </div>
                        <div class="state {{ demand.classStatus }}">
                            <span class="text">{{ demand.status|readable_enum('AccommodationDemandStatusType')|trans }}</span>
                        </div>
                        <div class="actions">
                            {% if is_granted(constant('App\\Enum\\AccommodationDemandVoterEnum::EDIT'), demand) %}
                                <a class="action accept fas fa-pen" href="{{ path('accommodation_demand_edit', {'id': demand.id}) }}"></a>
                                <a href="#" class="action decline fas fa-times" data-action="popup-on-click#click" data-route="accommodation_demand_status_abandoned"></a>
                            {% elseif is_granted(constant('App\\Enum\\AccommodationDemandVoterEnum::RESPOND'), demand) %}
                                <a href="#" class="action accept fas fa-check" data-action="popup-on-click#click" data-route="accommodation_demand_status_accepted"></a>
                                <a href="#" class="action decline fas fa-times" data-action="popup-on-click#click" data-route="accommodation_demand_status_refused"></a>
                            {% elseif demand.cohabitation is defined and is_granted(constant('App\\Enum\\CohabitationVoterEnum::SHOW'), demand.cohabitation) %}
                                <a href="{{ path('cohabitation_show', {'id': demand.cohabitation.id}) }}" class="btn btn-sm btn-secondary">
                                    <i class="fas fa-file-contract"></i> {{ 'cohabitation.show.button'|trans }}
                                </a>
                            {% elseif demand.refusingExplanation is not null%}
                                <div class="description {{ user == app.user?'full-width' }}">{{ demand.refusingExplanation }}</div>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/accommodation_demand/edit.html.twig
<div class="accommodation">
    {{ form_start(form) }}

    <div class="py-4">
        {{ form_row(form.description) }}
    </div>

    {{ form_rest(form) }}
    {{ form_errors(form) }}

    <div class="pt-4 text-right">
        <button type="submit" class="btn btn-primary btn--shadow">{{ 'actions.submit'|trans }}</button>
    </div>

    {{ form_end(form) }}
</div>