src/Entity/Event.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Enum\EventStatusEnum;
use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use EmailChecker\Constraints as EmailCheckerAssert;
use Fresh\DoctrineEnumBundle\Validator\Constraints as DoctrineAssert;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use libphonenumber\PhoneNumber;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Email;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 * @Vich\Uploadable
 */
class Event
{
    use TimestampableEntity;

    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date;

    /**
     * @var File|null
     *
     * @Vich\UploadableField(mapping="event", fileNameProperty="eventImageName")
     *
     * @Assert\File(
     *     maxSize="2M",
     *     mimeTypes={
     *         "image/png",
     *         "image/jpeg",
     *         "image/jpg",
     *         "image/gif",
     *         "image/bmp",
     *     }
     * )
     */
    private $eventImageFile;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $eventImageName;

    /**
     * @var Location
     *
     * @ORM\OneToOne(targetEntity="Location", cascade={"persist", "remove"})
     */
    private $location;

    /**
     * @var Association|null
     *
     * @ORM\ManyToOne(targetEntity="Association", inversedBy="events")
     */
    private $association;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="User", inversedBy="events", cascade={"persist"})
     */
    private $users;

    /**
     * @var string
     *
     * @ORM\Column(type="EventStatusType")
     * @DoctrineAssert\Enum(entity="App\Enum\EventStatusEnum")
     */
    private $status = EventStatusEnum::STATUS_DRAFT;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $isFree = true;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $isHandicapAccessible = false;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $isOpenAir = false;

    /**
     * @var array
     *
     * @ORM\Column(type="json")
     */
    private $languages = [];

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=180)
     * @Assert\Email(mode=Email::VALIDATION_MODE_HTML5)
     * @EmailCheckerAssert\NotThrowawayEmail
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column
     */
    private $lastname;

    /**
     * @var PhoneNumber|null
     *
     * @ORM\Column(type="phone_number", nullable=true)
     */
    private $phoneNumber;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $reminderNotificationSent = false;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $newParticipantNotificationToSend = false;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->location = new Location();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    public function setDate(?\DateTime $date): void
    {
        $this->date = $date;
    }

    public function getEventImageFile(): ?File
    {
        return $this->eventImageFile;
    }

    public function setEventImageFile(?File $eventImageFile): void
    {
        $this->eventImageFile = $eventImageFile;

        if (null !== $eventImageFile) {
            $this->updatedAt = new \DateTime();
        }
    }

    public function getEventImageName(): ?string
    {
        return $this->eventImageName;
    }

    public function setEventImageName(?string $eventImageName): void
    {
        $this->eventImageName = $eventImageName;
    }

    public function getLocation(): Location
    {
        return $this->location;
    }

    public function setLocation(Location $location): void
    {
        $this->location = $location;
    }

    public function getAssociation(): ?Association
    {
        return $this->association;
    }

    public function setAssociation(?Association $association): void
    {
        $this->association = $association;
    }

    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    public function isFree(): bool
    {
        return $this->isFree;
    }

    public function setIsFree(bool $isFree): void
    {
        $this->isFree = $isFree;
    }

    public function isHandicapAccessible(): bool
    {
        return $this->isHandicapAccessible;
    }

    public function setIsHandicapAccessible(bool $isHandicapAccessible): void
    {
        $this->isHandicapAccessible = $isHandicapAccessible;
    }

    public function isOpenAir(): bool
    {
        return $this->isOpenAir;
    }

    public function setIsOpenAir(bool $isOpenAir): void
    {
        $this->isOpenAir = $isOpenAir;
    }

    public function getLanguages(): array
    {
        return $this->languages;
    }

    public function setLanguages(array $languages): void
    {
        $this->languages = $languages;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    public function getFirstname(): string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): void
    {
        $this->firstname = $firstname;
    }

    public function getLastname(): string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): void
    {
        $this->lastname = $lastname;
    }

    public function getPhoneNumber(): ?PhoneNumber
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?PhoneNumber $phoneNumber): void
    {
        $this->phoneNumber = $phoneNumber;
    }

    public function isReminderNotificationSent(): bool
    {
        return $this->reminderNotificationSent;
    }

    public function setReminderNotificationSent(bool $reminderNotificationSent): void
    {
        $this->reminderNotificationSent = $reminderNotificationSent;
    }

    public function isNewParticipantNotificationToSend(): bool
    {
        return $this->newParticipantNotificationToSend;
    }

    public function setNewParticipantNotificationToSend(bool $newParticipantNotificationToSend): void
    {
        $this->newParticipantNotificationToSend = $newParticipantNotificationToSend;
    }

    public function isParticipating(User $user): bool
    {
        return $this->getUsers()->contains($user);
    }

    public function addUser(User $user): void
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
        }
    }

    public function removeUser(User $user): void
    {
        $this->users->removeElement($user);
    }

    public function clearUsers(): void
    {
        $this->users = new ArrayCollection();
    }
}

src/Entity/Location.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Location
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue
     */
    private $id;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $city;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $zipCode;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $district;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $street;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $country;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $countryCode;

    /**
     * @var float|null
     *
     * @ORM\Column(type="float", nullable=true)
     */
    private $latitude;

    /**
     * @var float|null
     *
     * @ORM\Column(type="float", nullable=true)
     */
    private $longitude;

    public function getId(): int
    {
        return $this->id;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): void
    {
        $this->city = $city;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(?string $zipCode): void
    {
        $this->zipCode = $zipCode;
    }

    public function getDistrict(): ?string
    {
        return $this->district;
    }

    public function setDistrict(?string $district): void
    {
        $this->district = $district;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): void
    {
        $this->street = $street;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }

    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    public function setCountryCode(?string $countryCode): void
    {
        $this->countryCode = $countryCode;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): void
    {
        $this->latitude = $latitude;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): void
    {
        $this->longitude = $longitude;
    }

    public function getReadableAddress(): string
    {
        $address = '';

        foreach ([$this->getCountry(), $this->getZipCode(), $this->getCity(), $this->getStreet()] as $field) {
            if (!empty($field)) {
                if (!empty($address)) {
                    $address .= ', ';
                }

                $address .= $field;
            }
        }

        return $address;
    }
}

src/Form/EventType.php
<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\Event;
use App\Service\LanguageManager;
use Misd\PhoneNumberBundle\Form\Type\PhoneNumberType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    private $languageManager;

    public function __construct(LanguageManager $languageManager)
    {
        $this->languageManager = $languageManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        /** @var Event $event */
        $event = $builder->getData();

        $builder
            ->add('name', TextType::class, [
                'required' => true,
                'label' => 'event.name',
            ])
            ->add('description', TextareaType::class, [
                'required' => true,
                'label' => 'event.description',
                'attr' => [
                    'data-controller' => 'textarea-autogrow',
                ],
                'help' => 'event.description.help',
            ])
            ->add('date', DateTimeType::class, [
                'required' => true,
                'label' => 'event.date',
                'data' => new \DateTime(),
                'minutes' => ['00', '15', '30', '45'],
                'years' => range((int) date('Y'), (int) date('Y') + 5),
            ])
            ->add('eventImageFile', FileType::class, [
                'required' => false,
                'attr' => [
                    'data-controller' => 'file-input',
                ],
                'label' => 'event.image',
            ])
            ->add('location', LocationFormType::class, [
                'required' => true,
                'label' => 'event.location',
                'data' => $event->getLocation(),
                'show_map' => true,
            ])
            ->add('isFree', CheckboxType::class, [
                'required' => false,
                'label_attr' => [
                    'class' => 'switch-custom',
                    'size' => 'md',
                ],
                'label' => 'event.is_free',
            ])
            ->add('isHandicapAccessible', CheckboxType::class, [
                'required' => false,
                'label_attr' => [
                    'class' => 'switch-custom',
                    'size' => 'md',
                ],
                'label' => 'event.is_handicap_accessible',
            ])
            ->add('isOpenAir', CheckboxType::class, [
                'required' => false,
                'label_attr' => [
                    'class' => 'switch-custom',
                    'size' => 'md',
                ],
                'label' => 'event.is_open_air',
            ])
            ->add('languages', ChoiceType::class, [
                'multiple' => true,
                'label' => 'event.languages',
                'attr' => [
                    'data-controller' => 'choices',
                ],
                'required' => false,
                'choices' => array_flip($this->languageManager->getEuropeanLanguages()),
            ])
            ->add('email', EmailType::class, [
                'required' => true,
                'label' => 'user.email',
            ])
            ->add('firstname', TextType::class, [
                'required' => true,
                'label' => 'user.firstname',
            ])
            ->add('lastname', TextType::class, [
                'required' => true,
                'label' => 'user.lastname',
            ])
            ->add('phoneNumber', PhoneNumberType::class, [
                'widget' => PhoneNumberType::WIDGET_COUNTRY_CHOICE,
                'required' => false,
                'label' => 'user.phone_number',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

templates/event/_image_event.html.twig
{% if event is defined and event is not null %}
    {% set url = vich_uploader_asset(event, 'eventImageFile') %}
{% endif %}

{% if url is not defined or url is null %}
    {% set url = asset('build/images/no_event.svg') %}
{% endif %}

<div class="photo">
    <img src="{{ url }}" alt="Event image"/>
</div>

templates/event/_sub_list.html.twig
{% if events | length > 0 %}
    <div class="pb-4">
        <div class="titled-p pt-4">
            <div class="title">{{ title }}</div>
            <div class="text">
                {% for event in events[:3] %}
                    {% include 'event/_sub_list_line.html.twig' %}
                {% endfor %}
            </div>

            {% if events | length > 3 %}
                <div data-controller="show-more-button">
                    <a class="d-block text-center" role="button" data-action="show-more-button#click">
                        {{ 'actions.show_more'|trans }}
                    </a>

                    <div class="d-none" data-show-more-button-target="content">
                        {% for event in events[3:] %}
                            {% include 'event/_sub_list_line.html.twig' %}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endif %}

templates/event/_sub_list_line.html.twig
<div class="row mb-4">
    <div class="col my-auto">
        {{ event.name }}
    </div>

    <div class="col my-auto">
        {{ event.date|format_datetime('short', 'short') }}
    </div>

    <div class="col-auto ml-auto mt-auto">
        {% include 'default/_list_actions.html.twig' with {
            'showButtons': [
                {
                    'path': path('event_show', {'id': event.id}),
                    'text': 'actions.show'|trans,
                    'class': 'btn-primary mb-2'
                }
            ]
        } %}
    </div>
</div>

templates/event/show.html.twig
<div class="mt-4" data-controller="popup-on-click" data-popup-on-click-id-value="{{ event.id }}">
    <div class="row align-items-center mb-4">
        <div class="col-4 col-md-2">
            {% include "event/_image_event.html.twig" %}
        </div>
        <div class="col-8">
            <div class="name">
                {{ event.name }}
            </div>

            {% if app.user %}
                <div class="tags">
                    <div class="tag {{ event.status == constant('App\\Enum\\EventStatusEnum::STATUS_OPEN') ? 'green' : event.status == constant('App\\Enum\\EventStatusEnum::STATUS_DRAFT') ? 'yellow' : 'red' }}">
                        {% if not is_granted(constant('App\\Enum\\UserRoleEnum::ROLE_ASSOCIATION')) and
                            event.status == constant('App\\Enum\\EventStatusEnum::STATUS_OPEN')
                        %}
                            {{ 'event.status.active'|trans }}
                        {% else %}
                            {{ event.status|readable_enum('EventStatusType')|trans }}
                        {% endif %}
                    </div>

                    {% if app.user in event.users %}
                        <div class="tag green">
                            {{ 'event.participation.tag'|trans }}
                        </div>
                    {% endif %}
                </div>
            {% endif %}
        </div>

        <div class="ml-auto row align-items-center mt-4 mt-sm-0">
            <div class="col-12 col-md">
                {{ 'event.association.by'|trans }}
            </div>
            <a href="{{ path('association_show', {'id': event.association.id}) }}" class="row align-items-center col-12 col-md-auto">
                <div class="col-2">
                    {% include 'association/_logo_association.html.twig' with {'association': event.association, 'class': 'small'} %}
                </div>
                <div class="col">
                    {{ event.association.name }}
                </div>
            </a>
        </div>
    </div>
    <div class="image-card vertical">
        <div class="content">
            <div class="text">
                <div class="py-4">
                    <div class="titled-p">
                        <div class="title">{{ 'event.description'|trans }}</div>
                        <div class="text">{{ event.description }}</div>
                    </div>
                    <div class="titled-p">
                        <div class="title">{{ 'event.date'|trans }}</div>
                        {% if app.user %}
                            <div class="text">{{ event.date|format_datetime('long', 'short') }}</div>
                        {% else %}
                            <div class="text">{{ event.date|format_date('long') }}</div>
                        {% endif %}
                    </div>
                    {% if app.user %}
                        <div class="titled-p">
                            <div class="title">{{ 'event.location'|trans }}</div>
                            <div class="text">{{ event.location.readableAddress }}</div>
                            <div class="map mt-4">
                                <div id="map-preview" class="interactive interactive-small"
                                     data-controller="show-location"
                                     data-location="{{ {'latitude': event.location.latitude, 'longitude': event.location.longitude}|json_encode }}"
                                >
                                </div>
                            </div>
                        </div>
                    {% endif %}

                    {% if event.languages|length > 0 %}
                        <div class="py-4 titled-p">
                            <div class="title">{{ 'event.languages'|trans }}</div>
                            <div class="tags">
                                {% for language in event.languages %}
                                    <div class="tag">
                                        {{ language|language_name|capitalize }}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}

                    <div class="bubble-icons py-4">
                        <div class="titled-p">
                            <div class="title">{{ 'event.details'|trans }}</div>
                            <div class="text">
                                • {{ event.isOpenAir ? 'event.type_of_place.outdoor'|trans : 'event.type_of_place.indoor'|trans }}
                            </div>
                            <div class="text">
                                • {{ event.isFree ? 'event.price.free'|trans : 'event.price.paid'|trans }}
                            </div>
                            {% if event.isHandicapAccessible %}
                                <div class="text">
                                    • {{ 'event.handicap_accessible'|trans }}
                                </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="bubble-icons py-4">
                        <div class="titled-p">
                            <div class="title">{{ 'event.contact'|trans }}</div>
                            <div class="text">{{ 'user.firstname'|trans ~ ': '~ event.firstname}}</div>
                            <div class="text">{{ 'user.lastname'|trans ~ ': '~ event.lastname}}</div>
                            <div class="text">{{ ('user.email'|trans ~ ': <a href="mailto:'~event.email~'">'~event.email~'</a>')|raw}}</div>

                            {% if event.phoneNumber %}
                                <div class="text">{{ ('user.phone_number'|trans ~ ': <a href="tel:'~event.phoneNumber|phone_number_format('INTERNATIONAL')~'">'~event.phoneNumber|phone_number_format('INTERNATIONAL')~'</a>')|raw}}</div>
                            {% endif %}

                        </div>
                    </div>

                    {% if app.user %}
                        <div class="titled-p">
                            <div class="title">{{ 'event.participants'|trans }}</div>

                            {% if is_granted(constant('App\\Enum\\UserRoleEnum::ROLE_ASSOCIATION')) %}
                                <nav>
                                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                                        <a class="nav-link active" id="nav-home-tab" data-toggle="tab"
                                           href="#participants_info" role="tab" aria-controls="participants_info"
                                           aria-selected="true">
                                            <i class="fas fa-info"></i>
                                        </a>
                                        <a class="nav-link" id="nav-list-tab" data-toggle="tab"
                                           href="#participants_list" role="tab" aria-controls="participants_list"
                                           aria-selected="false">
                                            <i class="fas fa-list"></i>
                                        </a>
                                    </div>
                                </nav>
                            {% endif %}

                            <div class="tab-content" id="nav-tabContent">
                                <div class="tab-pane fade show active" id="participants_info" role="tabpanel"
                                     aria-labelledby="nav-info-tab">
                                    <div class="text mt-3">{{ 'event.participants.all'|trans({'%nb%': event.users|length}) }}</div>
                                    <div class="text">{{ 'event.participants.senior'|trans({'%nb%': nbParticipantsSenior}) }}</div>
                                    <div class="text">{{ 'event.participants.young'|trans({'%nb%': nbParticipantsYoung}) }}</div>
                                </div>

                                {% if is_granted(constant('App\\Enum\\UserRoleEnum::ROLE_ASSOCIATION')) %}
                                    <div class="tab-pane fade" id="participants_list" role="tabpanel"
                                         aria-labelledby="nav-list-tab">
                                        <div class="ml-auto mt-3 mt-sm-0">
                                            <button id="download-csv" type="button" class="btn"><i
                                                        class="fas fa-download"></i> Export as CSV
                                            </button>
                                        </div>
                                        <div id="tabulator" data-roles="{{ roles|json_encode }}"
                                             data-genders="{{ genders|json_encode }}"
                                             data-boolean="{{ booleanFilter|json_encode }}"
                                             data-event-id="{{ event.id }}"></div>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>

            {% set showButtons = [] %}
            {% set approvalButtons = [] %}

            {% if not(app.user) %}
                {% set approvalButtons = approvalButtons|merge([
                    {
                        'route': 'login_modal',
                        'text': 'event.add_participation.button'|trans,
                        'class': 'btn-success mb-2',
                        'icon': 'fa-check-circle',
                        'referer': path('event_show', {'id': event.id}),
                        'title': 'map.login.title'
                    }
                ]) %}
            {% elseif is_granted(constant('App\\Enum\\EventVoterEnum::PARTICIPATE'), event) %}
                {% set approvalButtons = approvalButtons|merge([
                    {
                        'route': 'event_toggle_participation',
                        'text': isParticipating
                        ? 'event.remove_participation.button'|trans
                        : 'event.add_participation.button'|trans,
                        'class': isParticipating ? 'btn-danger mb-2' : 'btn-success mb-2',
                        'icon': isParticipating ? 'fa-times-circle' : 'fa-check-circle'
                    }
                ]) %}
            {% endif %}

            {% if is_granted(constant('App\\Enum\\EventVoterEnum::EDIT'), event) %}
                {% if event.status != constant('App\\Enum\\EventStatusEnum::STATUS_CANCELED') %}
                    {% set showButtons = showButtons|merge([
                        {
                            'path': path('event_edit', {'id': event.id}),
                            'icon': 'fa-pen',
                            'text': 'actions.edit'|trans,
                            'class': 'btn-primary mb-2'
                        }
                    ]) %}

                    {% if event.status == constant('App\\Enum\\EventStatusEnum::STATUS_DRAFT') %}
                        {% set approvalButtons = approvalButtons|merge([
                            {
                                'route': 'event_status_open',
                                'text': 'actions.publish'|trans,
                                'class': 'btn-success mb-2'
                            }
                        ]) %}
                    {% else %}
                        {% set approvalButtons = approvalButtons|merge([
                            {
                                'route': 'event_status_draft',
                                'text': 'actions.draft'|trans,
                                'class': 'btn-warning mb-2',
                                'icon': 'fa-eye-slash'
                            }
                        ]) %}
                    {% endif %}

                    {% set approvalButtons = approvalButtons|merge([
                        {
                            'route': 'event_status_canceled',
                            'text': 'actions.cancel'|trans,
                            'class': 'btn-danger mb-2',
                            'icon': 'fa-ban'
                        }
                    ]) %}
                {% endif %}
            {% endif %}

            {% if is_granted(constant('App\\Enum\\EventVoterEnum::DELETE'), event) %}
                {% set approvalButtons = approvalButtons|merge([
                    {
                        'route': 'event_delete',
                        'icon': 'fa-trash-alt',
                        'class': 'btn-danger mb-2',
                        'text': 'actions.delete'|trans
                    }
                ]) %}
            {% endif %}

            {% if showButtons|length > 0 or approvalButtons|length > 0 %}
                <div class="titled-p">
                    <div class="title">{{ 'actions'|trans }}</div>
                    <div class="text">
                        {% include 'default/_list_actions.html.twig' with {
                            'showButtons': showButtons,
                            'approvalButtons': approvalButtons
                        } %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>