src/Entity/Location.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 */
class Location
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue
     */
    private $id;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $city;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $zipCode;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $district;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $street;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $country;

    /**
     * @var string|null
     *
     * @ORM\Column(nullable=true)
     */
    private $countryCode;

    /**
     * @var float|null
     *
     * @ORM\Column(type="float", nullable=true)
     */
    private $latitude;

    /**
     * @var float|null
     *
     * @ORM\Column(type="float", nullable=true)
     */
    private $longitude;

    public function getId(): int
    {
        return $this->id;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): void
    {
        $this->city = $city;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(?string $zipCode): void
    {
        $this->zipCode = $zipCode;
    }

    public function getDistrict(): ?string
    {
        return $this->district;
    }

    public function setDistrict(?string $district): void
    {
        $this->district = $district;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): void
    {
        $this->street = $street;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }

    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    public function setCountryCode(?string $countryCode): void
    {
        $this->countryCode = $countryCode;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): void
    {
        $this->latitude = $latitude;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): void
    {
        $this->longitude = $longitude;
    }

    public function getReadableAddress(): string
    {
        $address = '';

        foreach ([$this->getCountry(), $this->getZipCode(), $this->getCity(), $this->getStreet()] as $field) {
            if (!empty($field)) {
                if (!empty($address)) {
                    $address .= ', ';
                }

                $address .= $field;
            }
        }

        return $address;
    }
}

src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use EmailChecker\Constraints as EmailCheckerAssert;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Email;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 *
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, \Serializable, PasswordAuthenticatedUserInterface
{
    use TimestampableEntity;

    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=180, unique=true, nullable=true)
     * @Assert\Email(mode=Email::VALIDATION_MODE_HTML5)
     * @EmailCheckerAssert\NotThrowawayEmail
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column
     */
    private $lastname;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday;

    /**
     * @var array
     *
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $password;

    /**
     * @var string|null
     */
    private $plainPassword;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @var Profile
     *
     * @ORM\OneToOne(targetEntity="Profile", inversedBy="user", cascade={"persist", "remove"})
     */
    private $profile;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="Message", mappedBy="sender", cascade={"persist", "remove"}))
     */
    private $messages;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="ThreadMetadata", mappedBy="participant", cascade={"persist", "remove"}))
     */
    private $threadMetadatas;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="ThreadFavorite", mappedBy="user", cascade={"persist", "remove"}))
     */
    private $threadFavorites;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Thread", mappedBy="users", cascade={"persist", "remove"})
     * @ORM\OrderBy({"lastMessageAt" : "DESC"})
     */
    private $threads;

    /**
     * @var Accommodation|null
     *
     * @ORM\OneToOne(targetEntity="Accommodation", mappedBy="senior", cascade={"persist", "remove"})
     */
    private $accommodation;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="AccommodationDemand", mappedBy="young", orphanRemoval=true)
     */
    private $accommodationDemands;

    /**
     * @var Location
     *
     * @ORM\OneToOne(targetEntity="Location", cascade={"persist", "remove"})
     */
    private $location;

    /**
     * @var Association|null
     *
     * @ORM\ManyToOne(targetEntity="Association", inversedBy="users")
     */
    private $association;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="Event", mappedBy="users", cascade={"persist", "remove"})
     * @ORM\OrderBy({"date" : "ASC"})
     */
    private $events;

    /**
     * @var UserNotification|null
     *
     * @ORM\OneToOne(targetEntity="UserNotification", cascade={"persist", "remove"})
     */
    private $userNotification;

    public function __construct()
    {
        $this->setProfile(new Profile());
        $this->messages = new ArrayCollection();
        $this->threads = new ArrayCollection();
        $this->threadMetadatas = new ArrayCollection();
        $this->threadFavorites = new ArrayCollection();
        $this->accommodationDemands = new ArrayCollection();
        $this->location = new Location();
        $this->events = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    public function getFirstname(): string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): void
    {
        $this->firstname = $firstname;
    }

    public function getLastname(): string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): void
    {
        $this->lastname = $lastname;
    }

    public function getBirthday(): ?\DateTime
    {
        return $this->birthday;
    }

    public function setBirthday(?\DateTime $birthday): void
    {
        $this->birthday = $birthday;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): void
    {
        $this->isVerified = $isVerified;
    }

    public function getProfile(): Profile
    {
        return $this->profile;
    }

    public function setProfile(Profile $profile): void
    {
        $this->profile = $profile;
        $profile->setUser($this);
    }

    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function getThreadMetadatas(): Collection
    {
        return $this->threadMetadatas;
    }

    public function getThreadFavorites(): Collection
    {
        return $this->threadFavorites;
    }

    public function getThreads(): Collection
    {
        return $this->threads;
    }

    public function getAccommodation(): ?Accommodation
    {
        return $this->accommodation;
    }

    public function setAccommodation(?Accommodation $accommodation): void
    {
        $this->accommodation = $accommodation;
        $accommodation->setSenior($this);
    }

    public function getAccommodationDemands(): Collection
    {
        return $this->accommodationDemands;
    }

    public function getLocation(): Location
    {
        return $this->location;
    }

    public function setLocation(Location $location): void
    {
        $this->location = $location;
    }

    public function getAssociation(): ?Association
    {
        return $this->association;
    }

    public function setAssociation(?Association $association): void
    {
        $this->association = $association;
    }

    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function getUserNotification(): ?UserNotification
    {
        return $this->userNotification;
    }

    public function setUserNotification(UserNotification $userNotification): void
    {
        $this->userNotification = $userNotification;
    }

    public function getFullName(): string
    {
        return $this->getFirstname().' '.$this->getLastname();
    }

    public function getUsername(): string
    {
        return $this->email;
    }

    public function getUserIdentifier(): string
    {
        return $this->getUsername();
    }

    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials(): void
    {
    }

    public function getAge(): ?int
    {
        $age = ($this->birthday instanceof \DateTimeInterface)
            ? date_diff(new \DateTime('now'), $this->birthday)->y
            : null;

        return (\is_int($age) && $age > 1) ? $age : null;
    }

    public function serialize(): string
    {
        return serialize([$this->id, $this->email, $this->password]);
    }

    public function unserialize($data): void
    {
        [
            $this->id,
            $this->email,
            $this->password
            ] = unserialize($data);
    }

    public function addMessage(Message $message): void
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setSender($this);
        }
    }

    public function removeMessage(Message $message): void
    {
        $this->messages->removeElement($message);
    }

    public function addThreadMetadata(ThreadMetadata $threadMetadata): void
    {
        if (!$this->threadMetadatas->contains($threadMetadata)) {
            $this->threadMetadatas->add($threadMetadata);
            $threadMetadata->setParticipant($this);
        }
    }

    public function removeThreadMetadata(ThreadMetadata $threadMetadata): void
    {
        $this->threadMetadatas->removeElement($threadMetadata);
    }

    public function addThreadFavorite(ThreadFavorite $threadFavorite): void
    {
        if (!$this->threadFavorites->contains($threadFavorite)) {
            $this->threadFavorites->add($threadFavorite);
            $threadFavorite->setUser($this);
        }
    }

    public function removeThreadFavorite(ThreadFavorite $threadFavorite): void
    {
        $this->threadFavorites->removeElement($threadFavorite);

templates/user/_image_user.html.twig
{% if user is defined and user is not null %}
    {% set url = vich_uploader_asset(user.profile, 'profilePictureFile') %}
{% endif %}

{% if url is not defined or url is null %}
    {% set url = asset('build/images/no_photo.png') %}
{% endif %}

<div class="photo {% if class is defined %}{{ class }}{% endif %}">
    <img src="{{ url }}" alt="Profile Picture"
            {% if tooltip is defined and tooltip is not null %}
                data-toggle="tooltip" data-placement="right"
                title="{{ tooltip }}"
            {% endif %}
    />
</div>

templates/user/_user_introduction.html.twig
<div class="row align-items-center mb-4">
    <div class="col-4 col-md-2">
        {% include "user/_image_user.html.twig" %}
    </div>
    <div class="col-8">
        <div class="name">
            {% if path != 'user_show' %}
                <a href="{{ path('user_show', {'id': user.id}) }}">
                    {{ user.fullName }}
                </a>
            {% else %}
                {{ user.fullName }}
            {% endif %}
        </div>

        <div class="tags">
            <div class="tag">
                {{ user|readable_role|trans }}
            </div>

            {% set isProfileApproved = user.profile.isApproved %}
            <div class="tag {{ isProfileApproved ? 'green' : 'red' }}">
                {{ isProfileApproved ? 'user.profile_verified'|trans : 'user.profile_not_verified'|trans }}
            </div>
        </div>
    </div>
</div>

templates/user/edit.html.twig
<div class="profile" data-controller="form-submission">
    {{ form_start(form, {
        'action': path(app.request.attributes.get('_route'),app.request.attributes.get('_route_params')),
        'attr': {'data-controller': 'homesharing-dynamic-form'}})
    }}

    {% include "user/_image_user.html.twig" %}
    {% if form.profile.profilePictureFile is defined %}
        {{ form_row(form.profile.profilePictureFile) }}
    {% endif %}

    {{ form_row(form.user.email) }}

    {% if form.user.plainPassword is defined %}
        {{ form_row(form.user.plainPassword.first) }}
        {{ form_row(form.user.plainPassword.second) }}
    {% endif %}

    {{ form_row(form.user.firstname) }}
    {{ form_row(form.user.lastname) }}

    {% if form.user.birthday is defined %}
        {{ form_row(form.user.birthday) }}
    {% endif %}

    {% if form.profile.gender is defined %}
        {{ form_row(form.profile.gender) }}
    {% endif %}

    {% if form.profile.description is defined %}
        {{ form_row(form.profile.description) }}
    {% endif %}

    {% if form.profile.languages is defined %}
        {{ form_row(form.profile.languages) }}
    {% endif %}

    {% if form.profile.hobbies is defined %}
        {{ form_row(form.profile.hobbies) }}
    {% endif %}

    {% if form.profile.university is defined %}
        {{ form_row(form.profile.university) }}
    {% endif %}

    {% if form.profile.studies is defined %}
        {{ form_row(form.profile.studies) }}
    {% endif %}

    {% if form.profile.passportFile is defined %}
        {{ form_row(form.profile.passportFile) }}
    {% endif %}

    {% if form.user.location is defined %}
        <div class="position-relative">
            {{ form_row(form.user.location) }}
        </div>
    {% endif %}


    {% if form.user.association is defined %}
        {{ form_row(form.user.association) }}
    {% endif %}

    {% if form.profile.phoneNumber is defined %}
        {{ form_row(form.profile.phoneNumber) }}
    {% endif %}

    {% if form.profile.international is defined %}
        <div class="pt-3">
            {{ form_row(form.profile.international) }}
        </div>
    {% endif %}

    {% if form.profile.showHomesharing is defined %}
        <div class="pt-3">
            <legend class="col-form-label">{{ 'user.homesharing'|trans }}</legend>
            {{ form_row(form.profile.showHomesharing) }}
        </div>
    {% endif %}

    {% if form.profile.motivation is defined %}
        <div data-homesharing-dynamic-form-target="motivation">
            {{ form_row(form.profile.motivation) }}
        </div>
    {% endif %}

    {% if form.profile.mobilityLetterFile is defined %}
        <div data-homesharing-dynamic-form-target="mobilityLetter">
            {{ form_row(form.profile.mobilityLetterFile) }}
        </div>
    {% endif %}

    {% if form.profile.currency is defined %}
        <div data-homesharing-dynamic-form-target="currency">
            {{ form_row(form.profile.currency) }}
        </div>
    {% endif %}

    {{ form_rest(form) }}
    {{ form_errors(form) }}

    <div class="pt-4 text-right">
        <button type="submit" class="btn btn-primary btn--shadow" data-form-submission-target="submitButton">
            {{ 'actions.submit'|trans }}
        </button>
    </div>

    {{ form_end(form) }}
</div>

templates/user/list.html.twig
{% extends 'account/_panels.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('users_list') }}
{% endblock %}

{% block title %}| {{ 'user.list.meta.title'|trans }}{% endblock %}

{% block dashboardContent %}
    <div class="panel">
        <div class="content">
            <div class="row px-3 pb-3">
                {% if is_granted(constant('App\\Enum\\UserVoterEnum::CREATE_SENIOR_ACCOUNT'), app.user) %}
                    <a href="{{ path('user_new') }}" class="btn btn-primary"><i class="fas fa-plus-circle"></i> {{ 'user.new_senior.meta.title'|trans }}</a>
                {% endif %}
                <div class="ml-auto mt-3 mt-sm-0">
                    <button id="download-csv" type="button" class="btn"><i class="fas fa-download"></i> Export as CSV</button>
                </div>
            </div>

            <div id="tabulator"
                 data-roles="{{ roles|json_encode }}"
                 data-associations="{{ associations|json_encode }}"
                 data-genders="{{ genders|json_encode }}"
                 data-boolean="{{ booleanFilter|json_encode }}"
                 data-filters="{{ app.request.query.all|json_encode }}"
            ></div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('users_list') }}
{% endblock javascripts %}

templates/user/new.html.twig
{% extends 'account/_panels.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('profile') }}
{% endblock %}

{% block title %}| {{ 'user.new_senior.meta.title'|trans }}{% endblock %}

{% block dashboardContent %}
    <div class="panel">
        <div class="header">
            <h1 class="title">{{ 'profile.other_user.title'|trans }}</h1>
        </div>
        <div class="content">
            {% include 'user/edit.html.twig' %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('profile') }}
{% endblock javascripts %}

templates/user/notifications.html.twig
{% form_theme form 'form/_fields.html.twig' %}

<div class="mx-3">
    {{ form_start(form, {'action': path('profile_notifications_edit')}) }}

    {% for type in types %}
        <h3 class="my-4">{{ ('user.notification.'~type)|trans }}</h3>

        {% for notif in form.notifications %}
            {% if type in notif.vars.id and not(notif.rendered) %}
                {{ form_row(notif) }}
            {% endif %}
        {% endfor %}
    {% endfor %}


    {{ form_errors(form) }}

    <div class="py-4 text-right">
        <input type="submit" class="btn btn-success" value="{{ 'actions.submit'|trans }}"/>
        <button type="button" data-dismiss="modal" class="btn modal-close">{{ 'actions.cancel'|trans }}</button>
    </div>

    {{ form_end(form) }}
</div>

templates/user/show.html.twig
{% include 'user/_user_introduction.html.twig' %}
<div class="content" data-controller="popup-on-click" data-popup-on-click-id-value="{{ user.id }}">
    {% if user == app.user or is_granted(constant('App\\Enum\\UserRoleEnum::ROLE_ASSOCIATION')) %}
        {% if user.email %}
            <div class="titled-p">
                <div class="title">{{ 'user.email'|trans }}</div>
                <div class="text"><a href="{{ 'mailto:'~user.email }}">{{ user.email }}</a></div>
            </div>
        {% endif %}

        {% if user.profile.phoneNumber %}
            <div class="titled-p">
                <div class="title">{{ 'user.phone_number'|trans }}</div>
                <div class="text">{{ user.profile.phoneNumber|phone_number_format('INTERNATIONAL') }}</div>
            </div>
        {% endif %}

        {% if user.profile.passportName %}
            <div class="titled-p">
                <div class="title">{{ 'user.passport'|trans }}</div>
                <div class="text">
                    {% set url = vich_uploader_asset(user.profile, 'passportFile') %}
                    <a href="{{ url }}" title="User ID" download>
                        <i class="fas fa-file-image fa-3x"></i>
                    </a>
                </div>
            </div>
        {% endif %}

        {% if user.profile.mobilityLetterName %}
            <div class="titled-p">
                <div class="title">{{ 'user.mobility_letter'|trans }}</div>
                <div class="text">
                    {% set url = vich_uploader_asset(user.profile, 'mobilityLetterFile') %}
                    <a href="{{ url }}" title="User mobility letter" download>
                        <i class="fas fa-file-image fa-3x"></i>
                    </a>
                </div>
            </div>
        {% endif %}
    {% endif %}

    {% if user.birthday is not null %}
        <div class="titled-p">
            <div class="title">{{ 'user.birthday'|trans }}</div>
            <div class="text">{{ user.birthday|format_date('long') }}</div>
        </div>
    {% endif %}

    {% if user.profile.gender is not null %}
        <div class="titled-p">
            <div class="title">{{ 'user.gender'|trans }}</div>
            <div class="text">{{ user.profile.gender|readable_enum('ProfileGenderType')|trans }}</div>
        </div>
    {% endif %}

    {% if user.profile.description is not null %}
        <div class="titled-p">
            <div class="title">{{ 'user.description'|trans }}</div>
            <div class="text">{{ user.profile.description|trans }}</div>
        </div>
    {% endif %}

    {% if not(user|is_manager) %}
        <div class="titled-p">
            <div class="title">{{ 'user.homesharing'|trans }}</div>
            <div class="text">{{ user.profile.showHomesharing ? 'yes'|trans : 'no'|trans }}</div>
        </div>

        {% if user.profile.showHomesharing and user.profile.motivation is not null %}
            <div class="titled-p">
                <div class="title">{{ 'user.motivation'|trans }}</div>
                <div class="text">{{ user.profile.motivation }}</div>
            </div>
        {% endif %}
    {% endif %}

    {% if user.location.country is not null %}
        <div class="titled-p">
            <div class="title">{{ 'user.live_in'|trans }}</div>
            <div class="text">{{ user.location.readableAddress }}</div>
        </div>
    {% endif %}

    {% if user.association is not null %}
        <div class="titled-p">
            <div class="title">{{ 'user.association'|trans }}</div>
            <div class="text">{{ user.association.name }}</div>
        </div>
    {% endif %}

    {% if user.profile.languages|length > 0 %}
        <div class="py-4 titled-p">
            <div class="title">{{ 'user.languages'|trans }}</div>
            <div class="tags">
                {% for language in user.profile.languages %}
                    <div class="tag">
                        {{ language|language_name|capitalize }}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    {% if user.profile.hobbies|length > 0 %}
        <div class="py-4 titled-p">
            <div class="title">{{ 'user.hobbies'|trans }}</div>
            <div class="tags">
                {% for hobby in user.profile.hobbies %}
                    <div class="tag">
                        {{ hobby.name }}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

    {% set showButtons = [] %}
    {% set approvalButtons = [] %}

    {% if path not in ['user_edit', 'profile_edit'] and is_granted(constant('App\\Enum\\UserVoterEnum::EDIT'), user) %}
        {% set path = app.user == user ? path('profile_edit') : path('user_edit', {id: user.id}) %}
        {% set showButtons = showButtons|merge([
            {
                'path': path,
                'icon': 'fa-pen',
                'text': 'actions.edit'|trans,
                'class': 'btn-primary mb-2'
            }
        ]) %}
    {% endif %}

    {% if is_granted(constant('App\\Enum\\UserVoterEnum::EDIT_NOTIFICATIONS'), user) %}
        {% set approvalButtons = approvalButtons|merge([
            {
                'route': 'profile_notifications_edit',
                'icon': 'fa-bell',
                'text': 'actions.edit_notifications'|trans,
                'class': 'btn-primary mb-2',
                'title': 'actions.edit_notifications'|trans
            }
        ]) %}
    {% endif %}

    {% if is_granted(constant('App\\Enum\\UserVoterEnum::SEND_MESSAGE'), user) %}
        {% set showButtons = showButtons|merge([
            {
                'path': path('messages', {'_fragment': 'new-thread', 'recipient': user.id}),
                'icon': 'fa-envelope',
                'text': 'actions.message'|trans,
                'class': 'btn-info mb-2'
            }
        ]) %}
    {% endif %}

    {% if is_granted(constant('App\\Enum\\UserVoterEnum::APPROVE'), user) %}
        {% set approvalButtons = approvalButtons|merge([
            {
                'route': 'user_approval',
                'class': 'btn-success mb-2'
            }
        ]) %}
    {% endif %}

    {% if is_granted(constant('App\\Enum\\UserVoterEnum::CLAIM_MANAGEMENT'), user) %}
        {% set approvalButtons = approvalButtons|merge([
            {
                'route': 'user_claim_management',
                'class': 'btn-success mb-2',
                'icon': 'fa-user-plus',
                'text': 'actions.manage'|trans
            }
        ]) %}
    {% endif %}

    {% if is_granted(constant('App\\Enum\\UserVoterEnum::DELETE'), user) %}
        {% set approvalButtons = approvalButtons|merge([
            {
                'route': 'user_delete',
                'icon': 'fa-trash-alt',
                'class': 'btn-danger mb-2',
                'text': 'actions.delete'|trans
            }
        ]) %}
    {% endif %}

    {% if showButtons|length > 0 or approvalButtons|length > 0 %}
        <div class="titled-p">
            <div class="title">{{ 'actions'|trans }}</div>
            <div class="text">
                {% include 'default/_list_actions.html.twig' with {
                    'showButtons': showButtons,
                    'approvalButtons': approvalButtons
                } %}
            </div>
        </div>
    {% endif %}
</div>